language: cpp

compiler:
  - clang

before_install:
  - sudo add-apt-repository -y ppa:andykimpe/cmake
  - sudo add-apt-repository -y ppa:boost-latest/ppa
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq g++-4.8
  - sudo apt-get install -qq cmake libreadline-dev uuid-dev libdb++-dev libdb-dev zip libssl-dev openssl build-essential python-dev autotools-dev libicu-dev libbz2-dev boost1.55

script:
  - cmake .
  - make larkx_client
